---

- name: Run OpenSCAP check
  hosts: all
  tasks:
    - name: Copy base C2S  RHEL7 XCCDF files to hosts
      get_url:
        url: http://192.168.8.248/ssg-rhel7-ds-1.2.xml
        dest: /tmp/ssg-rhel7-ds-1.2.xml
        mode: '0400'
    - name: Copy customization C2S  RHEL7 XCCDF files to hosts
      get_url:
        url: http://192.168.8.248/ssg-rhel7-ds-1-tailoring.xml
        dest: /tmp/ssg-rhel7-ds-1-tailoring.xml
        mode: '0400'
    - name: Run evaluation and store result and report files
      shell: |
        oscap xccdf eval --tailoring-file /tmp/ssg-rhel7-ds-1-tailoring.xml \
        --profile xccdf_org.ssgproject.content_profile_C2S --results-arf /tmp/{{ ansible_hostname }}-arf.xml \
        --results /tmp/{{ ansible_hostname }}-results.xml --report /tmp/{{ ansible_hostname }}-report.html \
        --oval-results --progress /tmp/ssg-rhel7-ds-1.2.xml > /tmp/{{ ansible_hostname }}-oval-results.txt 2>/dev/null
      ignore_errors: yes
    - name: Create Ansible playbook from results
      shell: |
        oscap xccdf generate fix --fix-type ansible \
        --result-id "" \
        --output /tmp/{{ ansible_hostname }}-ssg-rhel7-ds-playbook-result.yml \
        /tmp/{{ ansible_hostname }}-results.xml
    - name: Encode result file
      shell: cat /tmp/{{ ansible_hostname }}-oval-results.txt|base64 -w 0
      register: results
    - name: Encode report file
      shell: cat /tmp/{{ ansible_hostname }}-report.html|base64 -w 0
      register: report
    - name: Upload results to git
      shell: |
        curl -i -X PUT -H 'Authorization: token {{ token }}' \
        -d '{"message": "Oval results for {{ ansible_hostname }}", "content": "{{ results.stdout }}"}' \
        https://api.github.com/repos/lniesz/os-hardening/contents/results/{{ ansible_hostname }}-{{ ansible_date_time.epoch }}-oval-results.txt
    - name: Upload report to git
      uri:
        url: https://api.github.com/repos/lniesz/os-hardening/contents/results/{{ ansible_hostname }}-{{ ansible_date_time.epoch }}-report.html
        method: POST
        headers:
          Authorization: "Token {{ token }}"
        body_format: json
        body:
          "message": "Report for {{ ansible_hostname }}"
          "content": "{{ report.stdout }}"
